dongwu-kim/soomgo_wecode_commuting_app

app/model/useCase/signInSocialAuth.tsx, app/view/SignIn.tsx
- 로그인 버튼 활성화 기능 구현(예시)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)
=> [Steve] [ADD]구글 소셜 로그인 로직 추가

Navigation.tsx, android/app/google-services.json, app/presentation/components/main/Main.tsx
- Main layout && firebase DB android 연동
- Main layout 작성 -> milo
- Google services.json firebase url 작성 -> Hugo
=> [Hugo&Milo] [ADD] : Main Layout & Firebase DB 연동 (android fix)

Navigation.tsx, app/data/repository/SignInRepository.ts, app/data/repository/WorkLogRepository.ts, app/domain/useCase/WorkLogUseCase.ts, app/presentation/components/main/Main.tsx, app/presentation/components/workLog/WorkLog.tsx, app/presentation/components/workLog/WorkLogPresenter.tsx, app/presentation/hooks/worklog.ts, app/presentation/interface/IWorkLog.ts, app/utils/dayjs.ts, package-lock.json, package.json
-  WorkLog layout && dayjs logic && WorkLog load text logic 작성
- WorkLog layout & Text 제한 작성
- DB 연동 이전 dayjs 로직 작성
- WorkLog load text logic 작성
- DB 구조 변경
=> [Hugo] [ADD] : WorkLog layout && dayjs logic && WorkLog Load data logic

.prettierrc.js, app/data/repository/WorkLogRepository.ts, app/domain/useCase/WorkLogUseCase.ts, app/presentation/components/workLog/WorkLog.tsx, app/presentation/components/workLog/WorkLogPresenter.tsx, app/presentation/interface/IWorkLog.ts, app/utils/dayjs.ts
- WorkLog Load logic 변경 & 저장 or 수정 button toggle 작성
- WorkLog Load logic 변경 => presenter useCase 독립구조 반영
- 저장 or 수정 button toggle 작성 => 우선은 타이핑 시점부터 수정하기로 변경
=> [Hugo] [MODIFY] : WorkLog Load logic & SaveOrInsert button toggle

Navigation.tsx, app/presentation/components/main/Main.tsx, app/presentation/components/main/MainPresenter.tsx
- architecture arm64 제거 및 navigation 일부 수정
- architecture arm64 제거 및 navigation 일부 수정
=> [Hugo] [SETTING] : arm64 excluded && [MODIFY] : Main component navigation 수정

app/presentation/components/main/getLocation.tsx
- 위도경도 획득해서 주소로 변환
- geolocation으로 위도,경도 받은 값을
- resverse geocode API로 주소로 변환
- useEffect, useRef 이해하기가 어렵네요..
=> [steve] [ADD] Feature/get location 주소 받기

app/data/repository/MainWorkThisWeekRepository.ts, app/presentation/components/main/Main.tsx, app/presentation/components/main/MainPresenter.tsx, app/presentation/interface/IWorkThisWeek.ts, app/presentation/interface/IWorkTime.ts, app/utils/dayjs.ts, ios/soomgo_wecode_commute_app.xcodeproj/project.pbxproj, ios/soomgo_wecode_commute_app.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- MainPresenter 출퇴근시간 버튼 로직 구현
- Main WorkTime Presenter 출/퇴근 토글버튼 구현
- 버튼 클릭 시 출/퇴근 시간 MainView에 표시
- Main View에 현재 날짜 받아서 표시
- milo load오류 수정
=> [Milo] [MODIFY] Main WorkTime ToggleButton Presenter

app/presentation/hooks/useLocation.ts
- geolocation 위치정보 획득 로직 변경
- getCurrentPosition(일회성 현재위치 확인 및 위경도 반환) 에서 watchPosition(실시간 추적 및 위경도 반환)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)
=> [Steve][MODIFY] 지오로케이션 위치정보획득 로직 변경

app/data/repository/main/MainRepository.ts, app/presentation/components/main/Main.tsx, app/presentation/components/main/MainPresenter.tsx, app/presentation/components/signIn/SignInPresenter.tsx, app/presentation/hooks/useTodayWorkTimeLog.ts, app/presentation/hooks/useUserName.ts, app/presentation/hooks/useWeeklyWorkTime.ts, app/presentation/interface/IMainProps.ts, app/utils/dayjs.ts
- weekWorkTime Logic fix & userName & dailyWorkTime logic add
- weekWorkTime Logic 변경 : 버튼클릭 이후 실시간 반영 X => 실시간 반영
- userName view 표시 logic 작성
- dailyWorkTime view 표시 logic 작성
- 없습니다.
=> [Hugo] [FIX] : weekWorkTime Logic & [ADD] : userName & dailyWorkTime logic

android/app/src/main/AndroidManifest.xml, app/presentation/components/main/Main.tsx, app/presentation/components/main/MainPresenter.tsx, app/presentation/components/main/MainWorkThisWeek.tsx, app/presentation/hooks/useUserName.ts, app/presentation/hooks/useWeeklyWorkTime.ts, app/presentation/interface/IMainProps.ts, app/utils/dayjs.ts
- thisWeek workTime mapping & ACCESS_FINE_LOCATION permission 작성
- thisWeek workTime component mapping => view 표시
- ACCESS_FINE_LOCATION in manifest 작성 => steve
- 없습니다.
=> [Hugo & Steve] [ADD] : thisWeek workTime mapping & ACCESS_FINE_LOCATION

app/data/repository/main/MainRepository.ts, app/domain/useCase/main/MainUseCase.ts, app/presentation/components/main/Main.tsx, app/presentation/components/main/MainPresenter.tsx, app/presentation/interface/IMainProps.ts
- businessDay logic 작성
- businessDay logic => 공휴일에 출퇴근 버튼 입력 방지 구현
- 없습니다.
=> [Hugo] [ADD] : businessDay logic

app/data/repository/main/MainRepository.ts, app/presentation/components/main/Main.tsx, app/presentation/components/main/MainPresenter.tsx, app/presentation/hooks/useThisWeekWorkTime.ts, app/utils/dayjs.ts
- thisWeekWorkTime logic fix
- thisWeekWorkTime logic 내 log generate
- 없습니다.
=> [Hugo] [FIX] : thisWeekWorkTime logic fix

app/presentation/components/main/MainWorkThisWeek.tsx
- thisWeekWorkTime logic fix 2
- thisWeekWorkTime logic fix => undefined 출력 fix
=> [Hugo] [FIX] : thisWeekWorkTime logic fix 2

Navigation.tsx, app/presentation/components/meeting/Meeting.tsx, app/presentation/components/myPage/MyPage.tsx, package-lock.json, package.json
- bottom-tab navigator 추가
- Meeting, MyPage 빈 컴포넌트 추가
- bottom-tab navigator 연동
=> [Milo] [ADD] Feature/tab navigator

Navigation.tsx, app/presentation/components/main/Main.tsx, app/presentation/components/worktimedetail/WorkTimeDetail.tsx, package-lock.json
- 출퇴근 기록 stack 추가
- object로 출퇴근 정보 추가될 수 있도록 퍼블리싱
- 가독성 향상을 위한 배경색 지정
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)
=> [Steve] [ADD] Feature/woktime detail

Navigation.tsx, app/data/repository/workTimeDetail/WorkTimeDetailRepository.ts, app/domain/useCase/workTimeDetail/WorkTimeDetailUseCase.ts, app/presentation/components/worktimedetail/WorkTimeDetail.tsx, app/presentation/components/worktimedetail/WorkTimeDetailPresenter.tsx, app/presentation/hooks/useWorkTimeDetailLog.ts, app/presentation/interface/IWorkTimeDetailProps.ts, app/presentation/interface/IWorkTimeInfo.ts
- workTimeDetailLog logic 작성
- workTimeDetailLog logic (Date Picker, log 표시, DB data 변환)
=> [ADD] : workTimeDetailLog logic

app/presentation/components/DatePicker/DatePicker.tsx
- calendar Layout 작성
- calendar Layout 작성
=> [Hugo] [MODIFY] : calendar Layout

app/presentation/components/workLog/WorkLog.tsx
- Task Layout 작성
- Task Layout 작성
=> [Hugo] [MODIFY] : Task Layout

Navigation.tsx, android/app/src/main/AndroidManifest.xml, android/build.gradle, app/presentation/components/main/Main.tsx, app/presentation/components/main/MainWorkThisWeek.tsx, app/presentation/components/map/Maps.tsx, app/presentation/components/signIn/SignIn.tsx, app/presentation/components/worktimedetail/WorkTimeDetail.tsx, index.js, ios/Podfile, ios/Podfile.lock, ios/soomgo_wecode_commute_app.xcodeproj/project.pbxproj, ios/soomgo_wecode_commute_app/AppDelegate.m, ios/soomgo_wecode_commute_app/Info.plist, package-lock.json, package.json
- map view 추가
- main layout 수정
- 구글,애플 맵 추가
- main layout 수정
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)
=> [Steve][ADD] map view &&[MODIFY] Main layout

Navigation.tsx, app/presentation/components/main/Main.tsx, app/presentation/components/main/MainWorkThisWeek.tsx, app/presentation/components/workLog/WorkLog.tsx, ios/soomgo_wecode_commute_app/AppDelegate.m
- safeAreaView layout && 전체 배경 적용
- safeAreaView layout && 전체 배경 적용
=> [Hugo] [FIX] : safeAreaView fix

android/app/src/main/AndroidManifest.xml, android/build.gradle, app/data/repository/UsingFirebaseDB.ts, app/data/repository/main/MainRepository.ts, app/domain/useCase/main/MainUseCase.ts, app/presentation/components/DatePicker/DatePicker.tsx, app/presentation/components/main/Main.tsx, app/presentation/components/main/MainPresenter.tsx, app/presentation/components/main/MainWorkThisWeek.tsx, app/presentation/components/map/Maps.tsx, app/presentation/hooks/useLocation.ts, app/presentation/hooks/useWorkTimeAverage.ts, app/presentation/interface/IMainProps.ts, app/presentation/interface/IMapLocation.ts
…ogic 및 조건부 렌더 반영, 일 평균 근로시간 null 조건 추가
- TimeStamp 기준 변경, Maps 위치정보 전달, 출퇴근 toggle, 이번주 근무 공휴일 제외 logic 및 조건부 렌더 반영, 일 평균 근로시간 null 조건 추가
- TimeStamp 기준 변경 => serverTime으로 변경 ( 디바이스 시간 무시 )
- Maps 위치정보 전달 (latitude, longitude)
- 출퇴근 toggle (useEffect 조건 및 초기값 변경)
- 이번주 근무 공휴일 제외 logic 및 조건부 렌더 반영
- 일 평균 근로시간 null 조건 추가
=> [MODIFY] : TimeStamp 기준 변경, Maps 위치정보 전달, 출퇴근 toggle, 이번주 근무 공휴일 제외 등

app/data/repository/main/MainRepository.ts, app/data/repository/workLog/WorkLogRepository.ts, app/domain/useCase/workLog/WorkLogUseCase.ts, app/presentation/components/main/MainPresenter.tsx, app/presentation/components/main/MainWorkThisWeek.tsx, app/presentation/hooks/useWorkTimeAverage.ts
- 일평균 근로시간 logic 수정 & 근무예정 margin 추가 & 근무일지 지난주 일과 불러오기 추가
- 일평균 근로시간 logic 수정
- 근무예정 margin 추가
- 근무일지 지난주 일과 불러오기 추가
=> [Hugo] [MODIFY] : 일평균 근로시간 logic 수정 & 근무예정 margin 추가 & 근무일지 지난주 일과 불러오기 추가

app/data/repository/main/MainRepository.ts, app/data/repository/workTimeDetail/WorkTimeDetailRepository.ts
- load dayAvg workTime && detailLog logic
- load dayAvg workTime && detailLog logic
=> [MODIFY] : load dayAvg workTime && detailLog logic

app/presentation/components/meeting/Meeting.tsx, app/presentation/components/myPage/MyPage.tsx
=> [Hugo] [ADD] : 발표용 view 제작

app/presentation/components/main/MainPresenter.tsx, app/presentation/components/signIn/SignInPresenter.tsx, app/utils/dayjs.test.ts, app/utils/dayjs.ts
- jest && dayjs.test.ts
- jest && dayjs.test.ts
=> [Hugo] [ADD] jest && dayjs.test.ts

app/data/repository/UsingFirebaseDB.test.ts, app/data/repository/workLog/WorkLogRepository.test.ts, app/data/repository/workTimeDetail/WorkTimeDetailRepo.test.ts, jest.config.js
- UsingFirebaseDB test logic 추가
- usingServerTimeStamp logic 제외 작성 ( 4 / 5 )
=> [ADD] : UsingFirebaseDB test logic

app/data/repository/signIn/SignInRepository.test.ts, app/data/repository/workLog/WorkLogRepository.test.ts
- SignInRepository test logic 추가
- SignInRepository test logic (2 /2 ) 작성
=> [ADD] : SignInRepository test logic

app/data/repository/main/MainRepository.test.ts, app/data/repository/main/MainRepository.ts
- MainRepository test logic 작성
- MainRepository test logic (7 / 7) 작성
=> [ADD] : MainRepository test logic

.babelrc, app/data/repository/main/MainRepository.test.ts, app/data/repository/main/MainRepository.ts, app/data/repository/signIn/SignInRepository.test.ts, app/data/repository/workLog/WorkLogRepository.test.ts, app/data/repository/workTimeDetail/WorkTimeDetailRepository.test.ts, app/data/repository/workTimeDetail/WorkTimeDetailRepository.ts, app/domain/useCase/signIn/SignInUseCase.test.ts, app/domain/useCase/signIn/SignInUseCase.ts
- SignInUseCase test Logic && repository test transform async
- SignInUseCase test logic 작성
-  repository test logic 비동기 함수 test인 경우 async로 test 함수를 변경
=> [ADD] : SignInUseCase test Logic && repository test transform async

app/domain/useCase/workLog/WorkLogUseCase.test.ts, app/domain/useCase/workLog/WorkLogUseCase.ts
- WorkLogUseCase test 작성
- WorkLogUseCase test 작성
=> [Hugo] [ADD] : WorkLogUseCase test
